import { NextRequest, NextResponse } from 'next/server';
import { getSupabaseClientOrNull } from '../../../../../../lib/supabase';

/**
 * POST /api/beast-mode/janitor/vibe-ops/create-test
 * Create a new Vibe Ops test from plain English description
 */
export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const { description, type, repository } = body;

    if (!description || !description.trim()) {
      return NextResponse.json(
        { error: 'Test description is required' },
        { status: 400 }
      );
    }

    const userId = request.cookies.get('github_oauth_user_id')?.value;
    const supabase = await getSupabaseClientOrNull();

    // Generate test code (in production, this would use AI to generate proper test code)
    const testCode = `describe('${description}', () => {
  it('should ${description.toLowerCase()}', async () => {
    // Test code generated by Vibe Ops
    // Visual AI agent will execute this test
    expect(true).toBe(true);
  });
});`;

    let testId: string | null = null;

    if (supabase) {
      const { data, error } = await supabase
        .from('vibe_ops_tests')
        .insert({
          user_id: userId || null,
          repository: repository || null,
          description: description.trim(),
          type: type || 'happy-path',
          status: 'created',
          code: testCode,
        })
        .select()
        .single();

      if (error) {
        console.error('Failed to create test:', error);
        return NextResponse.json(
          { error: 'Failed to create test', details: error.message },
          { status: 500 }
        );
      }

      testId = data.id;
    } else {
      testId = Date.now().toString();
    }

    const test = {
      id: testId,
      description: description.trim(),
      type: type || 'happy-path',
      status: 'created',
      code: testCode,
      createdAt: new Date().toISOString()
    };

    return NextResponse.json(test);
  } catch (error: any) {
    console.error('Failed to create Vibe Ops test:', error);
    return NextResponse.json(
      { error: 'Failed to create test', details: error.message },
      { status: 500 }
    );
  }
}
