/**
 * Generated from User Story: US-0626
 * Title: context-aware suggestion (selection)
 * Category: AI Assistance - Code Suggestions
 * Priority: P1
 * 
 * As a developer
 * I want to get context-aware suggestions when selection
 * So that so that I can write better code
 * 
 * Generated by BEAST MODE API
 */

I can help you generate tests. Would you like me to create test files for your current code?