"use client";

import React, { useState } from 'react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '../ui/card';
import { Button } from '../ui/button';
import { Badge } from '../ui/badge';

interface VibeOpsTestCreatorProps {
  onTestCreated: (test: any) => void;
  onClose: () => void;
}

export default function VibeOpsTestCreator({ onTestCreated, onClose }: VibeOpsTestCreatorProps) {
  const [testDescription, setTestDescription] = useState('');
  const [testType, setTestType] = useState<'happy-path' | 'error-case' | 'edge-case'>('happy-path');
  const [creating, setCreating] = useState(false);
  const [createdTest, setCreatedTest] = useState<any>(null);

  const exampleTests = [
    "User can login and see dashboard",
    "Checkout flow completes successfully",
    "Form validation prevents invalid input",
    "Search returns relevant results",
    "User can update profile information"
  ];

  const handleCreateTest = async () => {
    if (!testDescription.trim()) return;

    setCreating(true);
    try {
      // TODO: Replace with actual API call
      const response = await fetch('/api/beast-mode/janitor/vibe-ops/create-test', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          description: testDescription,
          type: testType
        })
      });

      if (response.ok) {
        const test = await response.json();
        setCreatedTest(test);
        onTestCreated(test);
      } else {
        // Mock success for now
        const mockTest = {
          id: Date.now().toString(),
          description: testDescription,
          type: testType,
          status: 'created',
          code: `describe('${testDescription}', () => {\n  it('should ${testDescription.toLowerCase()}', async () => {\n    // Test code generated by Vibe Ops\n  });\n});`
        };
        setCreatedTest(mockTest);
        onTestCreated(mockTest);
      }
    } catch (error) {
      console.error('Failed to create test:', error);
    } finally {
      setCreating(false);
    }
  };

  if (createdTest) {
    return (
      <Card className="bg-slate-900 border-slate-800">
        <CardHeader>
          <CardTitle className="text-white">✅ Test Created</CardTitle>
          <CardDescription className="text-slate-400">
            Your test has been created and will run automatically
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-4">
          <div>
            <div className="text-sm text-slate-400 mb-2">Test Description:</div>
            <div className="text-white font-semibold">{createdTest.description}</div>
          </div>
          <div>
            <div className="text-sm text-slate-400 mb-2">Generated Code:</div>
            <pre className="bg-slate-950 p-4 rounded-lg text-xs text-slate-300 overflow-x-auto">
              <code>{createdTest.code}</code>
            </pre>
          </div>
          <div className="flex gap-4">
            <Button
              onClick={() => {
                setCreatedTest(null);
                setTestDescription('');
              }}
              className="flex-1 bg-cyan-600 hover:bg-cyan-700 text-white"
            >
              Create Another Test
            </Button>
            <Button
              onClick={onClose}
              variant="outline"
              className="border-slate-700 text-slate-300 hover:bg-slate-800"
            >
              Close
            </Button>
          </div>
        </CardContent>
      </Card>
    );
  }

  return (
    <Card className="bg-slate-900 border-slate-800">
      <CardHeader>
        <CardTitle className="text-white">Create Test in Plain English</CardTitle>
        <CardDescription className="text-slate-400">
          Describe what you want to test. Vibe Ops will generate and run the test automatically.
        </CardDescription>
      </CardHeader>
      <CardContent className="space-y-6">
        <div>
          <label className="block text-sm font-semibold text-white mb-2">
            Test Type
          </label>
          <div className="flex gap-2">
            {[
              { value: 'happy-path', label: 'Happy Path', icon: '✅' },
              { value: 'error-case', label: 'Error Case', icon: '❌' },
              { value: 'edge-case', label: 'Edge Case', icon: '⚠️' }
            ].map((type) => (
              <button
                key={type.value}
                onClick={() => setTestType(type.value as any)}
                className={`flex-1 px-4 py-2 rounded-lg border transition-all ${
                  testType === type.value
                    ? 'bg-cyan-600/20 border-cyan-500 text-cyan-400'
                    : 'bg-slate-800/50 border-slate-700 text-slate-300 hover:border-slate-600'
                }`}
              >
                <div className="text-lg mb-1">{type.icon}</div>
                <div className="text-xs">{type.label}</div>
              </button>
            ))}
          </div>
        </div>

        <div>
          <label className="block text-sm font-semibold text-white mb-2">
            Test Description
          </label>
          <textarea
            value={testDescription}
            onChange={(e) => setTestDescription(e.target.value)}
            placeholder="Describe what you want to test in plain English..."
            className="w-full bg-slate-950 border border-slate-700 rounded-lg px-4 py-3 text-white placeholder-slate-600 min-h-[120px] focus:outline-none focus:border-cyan-500"
          />
          <p className="text-xs text-slate-500 mt-2">
            Be specific about what should happen. Example: "User can login with valid credentials and see the dashboard"
          </p>
        </div>

        <div>
          <div className="text-sm font-semibold text-white mb-2">Example Tests</div>
          <div className="space-y-2">
            {exampleTests.map((example, idx) => (
              <button
                key={idx}
                onClick={() => setTestDescription(example)}
                className="w-full text-left px-3 py-2 bg-slate-800/50 hover:bg-slate-800 rounded-lg text-slate-300 hover:text-white transition-colors text-sm"
              >
                "{example}"
              </button>
            ))}
          </div>
        </div>

        <div className="flex gap-4 pt-4 border-t border-slate-800">
          <Button
            onClick={handleCreateTest}
            disabled={!testDescription.trim() || creating}
            className="flex-1 bg-cyan-600 hover:bg-cyan-700 text-white disabled:opacity-50"
          >
            {creating ? 'Creating Test...' : 'Create Test'}
          </Button>
          <Button
            onClick={onClose}
            variant="outline"
            className="border-slate-700 text-slate-300 hover:bg-slate-800"
          >
            Cancel
          </Button>
        </div>
      </CardContent>
    </Card>
  );
}

