/**
 * GitHub PR Creator
 * 
 * Creates GitHub Pull Requests with generated code for quality improvements.
 * Phase 3: Auto-Apply (PR Creation)
 */

const { Octokit } = require('@octokit/rest');

class GitHubPRCreator {
  constructor() {
    this.octokit = null;
  }

  /**
   * Initialize with GitHub token
   */
  initialize(token) {
    if (!token) {
      throw new Error('GitHub token required');
    }
    this.octokit = new Octokit({ auth: token });
  }

  /**
   * Create a PR with generated code files
   * @param {string} repo - Repository name (owner/repo)
   * @param {Object} improvementPlan - Improvement plan
   * @param {Array} generatedFiles - Generated code files
   * @param {Object} options - PR options
   * @returns {Object} PR creation result
   */
  async createImprovementPR(repo, improvementPlan, generatedFiles, options = {}) {
    const {
      branchPrefix = 'beast-mode-quality-improvement',
      title = `Quality Improvement: ${(improvementPlan.currentQuality * 100).toFixed(0)}% → ${(improvementPlan.finalQuality * 100).toFixed(0)}%`,
      baseBranch = 'main',
    } = options;

    if (!this.octokit) {
      throw new Error('GitHub client not initialized');
    }

    const [owner, repoName] = repo.split('/');
    if (!owner || !repoName) {
      throw new Error('Invalid repository format. Use: owner/repo');
    }

    try {
      // Step 1: Get default branch
      const { data: repoData } = await this.octokit.repos.get({ owner, repo: repoName });
      const defaultBranch = repoData.default_branch || baseBranch;

      // Step 2: Create branch
      const { data: defaultBranchData } = await this.octokit.repos.getBranch({
        owner,
        repo: repoName,
        branch: defaultBranch,
      });

      const branchName = `${branchPrefix}-${Date.now()}`;
      await this.octokit.git.createRef({
        owner,
        repo: repoName,
        ref: `refs/heads/${branchName}`,
        sha: defaultBranchData.commit.sha,
      });

      // Step 3: Create/update files
      const fileUpdates = [];
      for (const file of generatedFiles) {
        try {
          // Check if file exists
          let fileSha = null;
          try {
            const { data: existingFile } = await this.octokit.repos.getContent({
              owner,
              repo: repoName,
              path: file.fileName,
              ref: branchName,
            });
            if (Array.isArray(existingFile)) {
              // It's a directory, skip
              continue;
            }
            fileSha = existingFile.sha;
          } catch (error) {
            // File doesn't exist, will create new
          }

          // Create or update file
          const content = Buffer.from(file.code).toString('base64');
          
          await this.octokit.repos.createOrUpdateFileContents({
            owner,
            repo: repoName,
            path: file.fileName,
            message: `Add ${file.actionType}: ${file.fileName}`,
            content: content,
            branch: branchName,
            ...(fileSha && { sha: fileSha }),
          });

          fileUpdates.push({
            fileName: file.fileName,
            action: fileSha ? 'updated' : 'created',
            status: 'success',
          });
        } catch (error) {
          console.error(`[PR Creator] Failed to create/update ${file.fileName}:`, error);
          fileUpdates.push({
            fileName: file.fileName,
            action: 'failed',
            status: 'error',
            error: error.message,
          });
        }
      }

      // Step 4: Create PR
      const prBody = this.generatePRDescription(improvementPlan, generatedFiles, fileUpdates);
      
      const { data: pr } = await this.octokit.pulls.create({
        owner,
        repo: repoName,
        title,
        head: branchName,
        base: defaultBranch,
        body: prBody,
      });

      return {
        success: true,
        pr: {
          number: pr.number,
          url: pr.html_url,
          title: pr.title,
          state: pr.state,
        },
        branch: branchName,
        filesUpdated: fileUpdates.filter(f => f.status === 'success').length,
        filesFailed: fileUpdates.filter(f => f.status === 'error').length,
        fileUpdates,
      };
    } catch (error) {
      console.error('[PR Creator] Error creating PR:', error);
      return {
        success: false,
        error: error.message,
      };
    }
  }

  /**
   * Generate PR description
   */
  generatePRDescription(improvementPlan, generatedFiles, fileUpdates) {
    const successfulFiles = fileUpdates.filter(f => f.status === 'success');
    
    return `## Quality Improvement PR

This PR was automatically generated by BEAST MODE to improve repository quality.

### Quality Metrics

- **Current Quality:** ${(improvementPlan.currentQuality * 100).toFixed(1)}%
- **Target Quality:** ${(improvementPlan.targetQuality * 100).toFixed(1)}%
- **Estimated Final Quality:** ${(improvementPlan.finalQuality * 100).toFixed(1)}%
- **Improvement:** ${((improvementPlan.finalQuality - improvementPlan.currentQuality) * 100).toFixed(1)}%

### Generated Files

${successfulFiles.map(f => `- ✅ ${f.fileName} (${f.action})`).join('\n')}

### Improvement Plan

- **Iterations:** ${improvementPlan.iterations.length}
- **Total Files Generated:** ${generatedFiles.length}
- **Status:** ${improvementPlan.success ? '✅ Meets target' : '⚠️ Below target'}

### Next Steps

1. Review the generated files
2. Test the changes locally
3. Merge if satisfied

---

*Generated by [BEAST MODE](https://playsmuggler.com) Quality Improvement System*`;
  }
}

module.exports = new GitHubPRCreator();

