/**
 * Generated from User Story: US-0185
 * Title: Navigate definition (keyboard)
 * Category: Core Coding - Navigation
 * Priority: P0
 * 
 * As a developer
 * I want to navigate definition using keyboard
 * So that so that I can find code quickly
 * 
 * Generated by BEAST MODE API
 */

I can help you generate tests. Would you like me to create test files for your current code?