-- Migration7 Migration
-- Auto-generated by BEAST MODE Batch Generator
-- Generated: 2026-01-11T05:37:03.046Z

CREATE TABLE IF NOT EXISTS migration7 (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_migration7_created_at ON migration7(created_at DESC);
