-- Migration17 Migration
-- Auto-generated by BEAST MODE Batch Generator
-- Generated: 2026-01-11T05:37:03.046Z

CREATE TABLE IF NOT EXISTS migration17 (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_migration17_created_at ON migration17(created_at DESC);
