/**
 * Generated from User Story: US-0713
 * Title: Customize colors (basic)
 * Category: Developer Experience - Customization
 * Priority: P0
 * 
 * As a developer
 * I want to customize colors at basic level
 * So that so that the IDE works for me
 * 
 * Generated by BEAST MODE API
 */


              <pre>missing required error components, refreshing...</pre>
              <script>
                async function check() {
                  const res = await fetch(location.href).catch(() => ({}))

                  if (res.status === 200) {
                    location.reload()
                  } else {
                    setTimeout(check, 1000)
                  }
                }
                check()
              </script>