/**
 * Generated from User Story: US-0718
 * Title: command palette
 * Category: Developer Experience - Productivity
 * Priority: P0
 * 
 * As a developer
 * I want to use command palette
 * So that so that I can work faster
 * 
 * Generated by BEAST MODE API
 */


              <pre>missing required error components, refreshing...</pre>
              <script>
                async function check() {
                  const res = await fetch(location.href).catch(() => ({}))

                  if (res.status === 200) {
                    location.reload()
                  } else {
                    setTimeout(check, 1000)
                  }
                }
                check()
              </script>