/**
 * Generated from User Story: US-0288
 * Title: type-hints for dart
 * Category: Core Coding - Code Completion
 * Priority: P1
 * 
 * As a developer
 * I want to use type-hints when coding in dart
 * So that so that I can write dart code faster
 * 
 * Generated by BEAST MODE API
 */

I can help you generate tests. Would you like me to create test files for your current code?