/**
 * Generated from User Story: US-0717
 * Title: macros
 * Category: Developer Experience - Productivity
 * Priority: P1
 * 
 * As a developer
 * I want to use macros
 * So that so that I can work faster
 * 
 * Generated by BEAST MODE API
 */

I can help you generate tests. Would you like me to create test files for your current code?