/**
 * Generated from User Story: US-0287
 * Title: type-hints for kotlin
 * Category: Core Coding - Code Completion
 * Priority: P1
 * 
 * As a developer
 * I want to use type-hints when coding in kotlin
 * So that so that I can write kotlin code faster
 * 
 * Generated by BEAST MODE API
 */

I can help you generate tests. Would you like me to create test files for your current code?