/**
 * Generated from User Story: US-0728
 * Title: shortcuts
 * Category: Developer Experience - Learning
 * Priority: P1
 * 
 * As a developer
 * I want to access shortcuts
 * So that so that I can learn the IDE
 * 
 * Generated by BEAST MODE API
 */

I can help you generate tests. Would you like me to create test files for your current code?